Controllers films users
zg-devj/java-filmorate pull request #1
Opened 2023-02-10 07:05 UTC by zg-devj

2023-02-10 19:44 UTC, TomattmanYandex requested changes
Привет, отличная работа, надо поправить всякие мелочи

2023-02-10 19:44 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
тут форматирование кажется поехало

2023-02-10 19:44 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        ValidateService.isEmptyList(films.size(), "Фильмов не существует");
обычно валидируют только входные значение

2023-02-10 19:44 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        ValidateService.isEmptyList(users.size(), "Пользователей не существует");
то же самое что и в предыдущем

2023-02-10 19:44 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int id;
лучше использовать класс обертку а не примитив
null значение будет значить что значение еще не проставили, и это поможет избежать путаницы

2023-02-10 19:44 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int duration;
и снова, коментарий про обертку

2023-02-10 19:44 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private int id;
тот же комментарий про примитивы

2023-02-10 19:44 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/utils/ValidateServiceTest.java
> +    public void test_isEmptyStringField() {
эти тесты хороши, но лучше сделать их в комбинации с контроллером, что при добавлении неправильного значения падает ошибка, а то вдруг эти методы не используются
Я думаю у вас в дальнейшем будет темя про интеграционные и юнит тесты

2023-02-11 06:00 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        ValidateService.isEmptyList(films.size(), "Фильмов не существует");
Убрал.

2023-02-11 06:00 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        ValidateService.isEmptyList(users.size(), "Пользователей не существует");
Убрал

2023-02-11 06:01 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
Исправил

2023-02-11 06:07 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int duration;
Исправил.

2023-02-11 06:07 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int id;
Исправил.

2023-02-11 06:08 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private int id;
Исправил.

2023-02-11 06:31 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int duration;
Но не пойму зачем здесь предполагать null значение, если по условию, продолжительность фильма положительна, а фильма со значением 0 не существует физически? При типе **int** :
<0 -  код 400
0 - код 400
null - код 400
А если поставить тип **Integer**, результаты все равно должны быть такими же как выше. 
Единственное можно с типом int добавить аннотацию @NotNull, потому, что с аннотацией @Positive проходят значения null.

2023-02-11 08:41 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int duration;
Хотя int не может быть и так null.

2023-02-11 18:19 UTC, zg-devj commented on src/test/java/ru/yandex/practicum/filmorate/utils/ValidateServiceTest.java
> +    public void test_isEmptyStringField() {
Доделал

2023-02-11 18:50 UTC, TomattmanYandex approved these changes
отлично, принято

2023-02-11 20:16 UTC, merged