Develop
zg-devj/java-filmorate pull request #14
Opened 2023-04-19 17:32 UTC by zg-devj

2023-04-20 15:05 UTC, TomattmanYandex requested changes
Привет, работа хорошая, есть непонятные моменты, и в некоторых моментах есть очень сильное усложнение запросов, чаще проще сделать вместо одного запроса два, и на уровне сервиса их скомбинировать, чем делать один но универсальный запрос
комментарии в пулл реквесте и да
есть требования по количеству вложенных подзапросов, чтобы было не больше одного, проверьте пожалуйста все запросы, чтобы удовлетворяли этому требованию

2023-04-20 15:05 UTC, TomattmanYandex commented on README.md
Обязательно должно быть описание того, какие задачи выполнила группа

2023-04-20 15:05 UTC, TomattmanYandex commented on README.md
и лучше детально, кто что сделал

2023-04-20 15:05 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ReviewController.java
> +            @RequestParam Optional<Long> filmId,
зачем параметр делать optional нам же он в любом случае нужен

2023-04-20 15:05 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ReviewController.java
> +            @RequestParam Optional<Long> filmId,
чтобы сделать film id опциональным его надо сделать не обязательным параметром

2023-04-20 15:05 UTC, TomattmanYandex commented on src/main/resources/schema.sql
> +    like_it   SMALLINT NOT NULL CHECK (like_it = 1 OR like_it = -1),
почему значение числовое а не BOOLEAN
BOOLEAN позволяет как раз иметь два значение например true - like , false - dislike

2023-04-20 15:05 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/services/ReviewService.java
> +    public List<Review> findAllReviews(Optional<Long> filmId, int limit) {
обычно для того чтобы был разный функционал в зависимости от параметров - перегружают метод
только с числовым параметром - ревью всех в определенном количестве, два параметра- ревью конкретного в нужном количестве

2023-04-20 15:05 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/services/ReviewService.java
> +        ValidateUtil.validNumberNotNull(id, "id отзыва не должно быть null.");
Id тут не сможет быть null потому что если будет null в строке пути, то не подойдет по патерну число в пути и будет ошибка с поиском метода контроллера

2023-04-20 15:05 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/services/ReviewService.java
> +        Review review = reviewStorage.findReviewById(id).orElseThrow(
так как лог не содержит данных о возвращенном обьекте, то можно сначала сделать лог
а потом 
return reviewStorage.findReviewById(id).orElseThrow(() -> new NotFoundException("message"))
 текущий код выглядит странно и избыточно

2023-04-20 15:05 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/services/ReviewService.java
> +        eventStorage.addEvent(review.getUserId(), review.getReviewId(), EventStorage.TypeName.REVIEW,
супер, вариант как можно улучшить еще чуть чуть - сделать метод в конкретно этом сервисе который будет принимать на один параметр меньше, все равно для всех ивентов в этом сервисе тип будет ревью

2023-04-20 15:05 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/services/ReviewService.java
> +    public void likeReview(Long reviewId, Long userId) {
так как логика создания лайка и дизлайка не отличается ничем кроме параметра, вместо двух методов, сделать один с параметром, или вариант еще сделать третий метод с тремя параметрами, а в этих просто его вызывать

2023-04-20 15:05 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +package ru.yandex.practicum.filmorate.storage.review;
ревью я смотрю первым поэтому этот комент будет здесь
создание отдельного пакет под каждую пару интерфейс дао - избыточно
обычно поступают следующим образом, storage - пакет где все интерфейсы а в нем пакет impl где будут все имплементации

2023-04-20 15:05 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +    private final ReviewUserStorage reviewUserStorage;
обычно если есть интерфейс то создаем сервисы по интерфейсу

2023-04-20 15:05 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/reviewuser/ReviewUserDbStorage.java
> +public class ReviewUserDbStorage implements ReviewUserStorage {
мне нравится что под отдельную таблицу отдельный DAO класс

2023-04-20 15:05 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/reviewuser/ReviewUserDbStorage.java
> +    public void createLike(Long reviewId, Long userId) {
createLike и createDislike лучше заменить одним методом с третьим параметром

2023-04-20 15:05 UTC, TomattmanYandex commented on src/main/resources/schema.sql
> +    PRIMARY KEY (review_id, user_id)
очень классно что добавлен ключ, единственное мне кажется что стоит сделать это не первичным ключем, а просто добавить ограничение на уникальность

2023-04-20 15:05 UTC, TomattmanYandex commented on src/main/resources/schema.sql
> +    film_id     BIGINT REFERENCES films (film_id)
можно добавить ограничение на уникальность фильма и пользователя, чтобы на уровне базы ограничить возможность создать несколько ревью одним пользователем

2023-04-20 15:05 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public List<Film> searchForMoviesByDescription(String query, String by) {
сложно, можно упростить
на уровне сервиса понять по какому параметру мы ищем
создать сет фильмов 
если ищем по названию, то сделать поиск только по имени и результат добавить в сет
если ищем по режиссёру, то сделать поиск по режиссёру и результат добавить в сер
если ищем по обоим, то уже два действия выполнены(а сет сделал чтобы не было дубликатов)
после возвращаем сет

2023-04-20 15:05 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public List<Film> searchForMoviesByDescription(String query, String by) {
а на уровне хранилища будут два метода по проще, которые один возвращает по режиссеру, второй по имени

2023-04-20 15:05 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            @RequestParam Long userId, Long friendId
второй параметр не помечен анотацие @RequestParam

2023-04-20 15:05 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public List<Film> sharedUserMovies(
Почему метод называется shared а не common

2023-04-20 15:05 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                "ORDER BY rate DESC";
в запросе нету части where поэтому непонятно как будут ограничены только фильмы общие для двух пользователей

2023-04-20 15:05 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +    public List<Film> sharedUserMovies(Long userId, Long friendId) { // получение общих фильмов пользователей
почему shared если common

2023-04-20 15:05 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sql = "SELECT f.*, m.mpa_name, COALESCE(s.count_like, 0) AS rate " +
1) в запросах не допускается 2 и больше подзапроса
2) снова слишком сложно
как сдлеать проще, во первых сделать два запроса, первый это нахождение id пользователей с похожими вкусами - второй - получить рекомендации по id пользователя и списку id похожих пользователей
а текущий запрос понять ну очень тяжело

2023-04-20 15:05 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                "WHERE user_id = " +
прочитать запрос нереально

2023-04-20 15:05 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmCleanupService.java
> +public class FilmCleanupService {
не совсем понятно почему этот функционал и функционал по удалению фильма вынесен в отдельный сервис

2023-04-20 15:05 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            @RequestParam Optional<Integer> genreId,
если значения не обязательны, то делаем required = false но принимаем все равно обычные объекты вместо jptional

2023-04-20 15:52 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +    private final ReviewUserStorage reviewUserStorage;
У сервиса нет интерфейса.

2023-04-20 15:59 UTC, zg-devj commented on src/main/resources/schema.sql
> +    PRIMARY KEY (review_id, user_id)
Я в интернете не находил варианта с ограничением на уникальность, все время попадался м использованием primary key. Буду иметь в виду другой вариант. Спасибо.

2023-04-20 19:04 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ReviewController.java
> +            @RequestParam Optional<Long> filmId,
Исправил

2023-04-20 19:07 UTC, TimMug28 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public List<Film> searchForMoviesByDescription(String query, String by) {
Исправлено

2023-04-20 19:10 UTC, ivoylov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sql = "SELECT f.*, m.mpa_name, COALESCE(s.count_like, 0) AS rate " +
Fixed

2023-04-20 19:10 UTC, ivoylov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                "WHERE user_id = " +
Fixed

2023-04-20 19:11 UTC, TimMug28 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            @RequestParam Long userId, Long friendId
Исправил

2023-04-20 19:12 UTC, TimMug28 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public List<Film> sharedUserMovies(
Исправил

2023-04-20 19:12 UTC, TimMug28 commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +    public List<Film> sharedUserMovies(Long userId, Long friendId) { // получение общих фильмов пользователей
Исправил

2023-04-20 19:33 UTC, TimMug28 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                "ORDER BY rate DESC";
Исправил

2023-04-20 19:55 UTC, zg-devj commented on src/main/resources/schema.sql
> +    like_it   SMALLINT NOT NULL CHECK (like_it = 1 OR like_it = -1),
Я думал о boolean. Мне показалась более логичным положительный и отрицательный отзыв 1/-1 
COALESCE(sum(ru.like_it),0) AS useful  да и запрос понятней. чем
SELECT r.*,
       (count(nullif(ru.LIKE_IT, false)) - (count(nullif(ru.LIKE_IT, true)))) AS useful
FROM reviews AS r
         LEFT JOIN review_user AS ru on r.review_id = ru.review_id
WHERE r.review_id = ?
GROUP BY r.review_id;

2023-04-20 20:00 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/services/ReviewService.java
> +    public List<Review> findAllReviews(Optional<Long> filmId, int limit) {
Исправил в соответствии с замечанием выше.

2023-04-20 20:02 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ReviewController.java
> +            @RequestParam Optional<Long> filmId,
filmId не обязательный параметр, в соответствии с заданием

2023-04-20 20:08 UTC, molestov commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmCleanupService.java
> +public class FilmCleanupService {
Исправлено

2023-04-20 20:11 UTC, molestov commented on src/main/java/ru/yandex/practicum/filmorate/services/ReviewService.java
> +        eventStorage.addEvent(review.getUserId(), review.getReviewId(), EventStorage.TypeName.REVIEW,
Ок, принял к сведению.

2023-04-20 20:15 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/services/ReviewService.java
> +        ValidateUtil.validNumberNotNull(id, "id отзыва не должно быть null.");
Исправил. (+ исправил в аналогичных методах в других сервисах)

2023-04-20 20:24 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/services/ReviewService.java
> +        Review review = reviewStorage.findReviewById(id).orElseThrow(
Лог выводится в случае ошибки и содержит идентификатор. Я писал об этом при сдаче прошлого ТЗ.
По этой теме первое что нашел : https://stackoverflow.com/questions/71546006/how-to-log-error-and-throw-an-exception-inside-orelsethrow-clause

2023-04-20 20:46 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/services/ReviewService.java
> +    public void likeReview(Long reviewId, Long userId) {
Исправил.

2023-04-20 20:48 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/storage/reviewuser/ReviewUserDbStorage.java
> +    public void createLike(Long reviewId, Long userId) {
Исправил.

2023-04-20 21:10 UTC, zg-devj commented on src/main/resources/schema.sql
> +    film_id     BIGINT REFERENCES films (film_id)
Исправил.

2023-04-20 21:16 UTC, zg-devj commented on src/main/resources/schema.sql
> +    PRIMARY KEY (review_id, user_id)
Этот вариант оставил. Ниже есть замечание, где использовал UNIQUE.

2023-04-20 21:26 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            @RequestParam Optional<Integer> genreId,
Исправил.

2023-04-21 05:55 UTC, zg-devj commented on README.md
Добавил скрин Boad View

2023-04-21 05:56 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +package ru.yandex.practicum.filmorate.storage.review;
Исправил.

2023-04-21 15:58 UTC, TomattmanYandex requested changes
Привет. Отличная работа, задание выполнено хорошо. Справились отлично. В качестве плюсов - это сама работа.
в качестве минусов - все еще можно было бы уменьшить некоторые файлы, самый яркий пример это FIlmDbStorage  в нем множество раз повторяется один и тот же запрос, точнее часть одного и того же запроса, Если ее вынести в отдельную переменную (часть Select) и в методах к ней добавлять часть с условием, мне кажется можно было бы сократить этот файл минимум на треть, да и сама поддержка и изменение стали бы легче, ведь в одном месте изменить гораздо легче чем в нескольких.
Отправлю задание на переработку чтобы еще раз, чтобы могли это поправить, если будт лениво, или просто не хочется, то просто скидывайте приму

2023-04-21 15:58 UTC, TomattmanYandex commented on src/main/resources/schema.sql
> +    like_it   SMALLINT NOT NULL CHECK (like_it = 1 OR like_it = -1),
обычно если есть два возможных значения то это как сигнал что стоит использовать boolean
Если не хочется использовать boolean то тогда альтернативный вариант это строка либо число но с привязкой значения через enum ( в случае числа - индекс элемента в enum)
Но с точки зрения читаемости базы все же лучше вариант либо true false либо енам и строка

2023-04-21 15:58 UTC, TomattmanYandex commented on src/main/resources/schema.sql
> +    like_it   SMALLINT NOT NULL CHECK (like_it = 1 OR like_it = -1),
с текущей реализацией не очень понятно за то отвечает каждое значение, и это главный минус

2023-04-21 15:58 UTC, TomattmanYandex commented on src/main/resources/schema.sql
> +    like_it   SMALLINT NOT NULL CHECK (like_it = 1 OR like_it = -1),
но исправлять не обязательно

2023-04-21 15:58 UTC, TomattmanYandex commented on src/main/resources/schema.sql
> +    PRIMARY KEY (review_id, user_id)
первичный ключ хорош тем что добавляет индексы для поиска по нему, но индексы на данные по которым мы чаще изменяем данные чем ищем - не самый лучший в плане оптимизации момент

2023-04-21 15:58 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +    private final ReviewUserStorage reviewUserStorage;
тут был коммент но так как он улетел, то просто отвечу на него так
в реальных проектах уже очень редко  пишут DAO классы, и все взаимодействие с базой чаще всего идет через интерфейс и сгенеренный спрингом код, 
это одна из причин почему мне кажется тут вас просили сделать интерфейс
второй повод, это потому что изначально было две имлементации, и чтобы научиться инжектить бины если есть несколько реализаций

2023-04-21 16:37 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +    private final ReviewUserStorage reviewUserStorage;
В теории был акцент на DAO. От туда все. Про вторую имплементацию в реализующую хранение в памяти наставник сказал на вэбинаре, что можно еe удалить.

2023-04-21 16:43 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorage.java
> +    private final ReviewUserStorage reviewUserStorage;
Как раз изучаю Spring Data JDBC и Spring data JPA

2023-04-21 21:14 UTC, TomattmanYandex approved these changes
Принято

2023-04-21 21:15 UTC, TomattmanYandex approved these changes
Принято

2023-04-21 21:16 UTC, TomattmanYandex approved these changes
Принято

2023-04-21 21:16 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    @GetMapping("/{id}/recommendations")
Кажется если я комента не оставлю это не засчитается как ревью

2023-04-22 04:54 UTC, merged