Add database
zg-devj/java-filmorate pull request #3
Opened 2023-03-27 11:01 UTC by zg-devj

2023-03-27 14:38 UTC, TomattmanYandex requested changes
схема базы данных не соответствует изображению, за счет этого некоторые важные моменты надо переделать, а так работа отличная

2023-03-27 14:38 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +                    ValidateUtil.throwNotFound(String.format("Фильма с id=%d не существует.", id));
зачем выделять для этого отдельный метод, а после этого еще и возвращать null после ошибки выполнение все равно не дойдет до следующей строчки

2023-03-27 14:38 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +                    ValidateUtil.throwNotFound(String.format("Фильма с id=%d не существует.", id));
return filmStorage.findFilmById(id).orElseThrow(NotFoundException::new);

2023-03-27 14:38 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +                    ValidateUtil.throwNotFound(String.format("Фильма с id=%d не существует.", id));
Ну или как в следующем методе

2023-03-27 14:38 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +        Film updated = filmStorage.updateFilm(film);
а если изменены жанры, как их обновить

2023-03-27 14:38 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sql = "SELECT * FROM films ORDER BY rate DESC LIMIT ?";
необходимо сделать join с подсчетом лайков

2023-03-27 14:38 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
>  public class FilmService {
не хватает жанров у возвращаемых фильмов

2023-03-27 14:38 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        if (film.getGenres() != null && film.getGenres().size() > 0) {
лучше это сделать отдельным методом, и вызывать его с уровня сервиса

2023-03-27 14:38 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            if (film.getGenres() != null && film.getGenres().size() >= 0) {
аналогично

2023-03-27 14:38 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public void increaseFilmRate(Long filmId) {
рейтинг фильма, это количество лайков, для этого не нужно дополнительное поле

2023-03-27 14:38 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmganre/FilmGenreDbStorage.java
> +        String sql = "INSERT INTO film_genre "
какое то усложнение, можно добавить ограничение на уникальность нас столбец в базе

2023-03-27 17:17 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +                    ValidateUtil.throwNotFound(String.format("Фильма с id=%d не существует.", id));
Выделил в отдельный метод, чтобы не дублировать код. 
Код метода содержит логирование при исключении.
На отсутствие return null,  ругается компилятор. 
(java: incompatible types: bad return type in lambda expression
    missing return value)
PS: Изначально делал как вы предложили,

2023-03-27 17:21 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +        Film updated = filmStorage.updateFilm(film);
Все жанры обновляются в storage. 
filmGenreStorage.deleteGenresByFilmId(key);
filmGenreStorage.create(key, film.getGenres());

2023-03-27 17:27 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sql = "SELECT * FROM films ORDER BY rate DESC LIMIT ?";
Кол-во лайков существует в поле rate. Т.к. в ТЗ было указано, что пользователь пользователь может поставить лайк только один раз то данные о лайке находятся в таблице film_like, а всего лайков в поле rate. Запрос  findPopularFilms на мой взгляд, достаточно частый запрос,  то такой способ запроса более продуктивней.

2023-03-27 17:29 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
>  public class FilmService {
Все фильмы, возвращаются с жанрами, в противном случае тесты Postman не были бы пройдены.

2023-03-27 17:31 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public void increaseFilmRate(Long filmId) {
Выше написал, почему дополнительное поле продуктивней. Четкого указания на этот счет в ТЗ не было.

2023-03-27 17:38 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmganre/FilmGenreDbStorage.java
> +        String sql = "INSERT INTO film_genre "
В таблице стоит ограничение (PRIMARY KEY (film_id, genre_id)), которое не позволит существованию двух одинаковым записям.
Можно было бы сделать запрос в цикле, но вариант с единственным запросом (jdbcTemplate.batchUpdate) мне показался более интересней.

2023-03-27 18:02 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        if (film.getGenres() != null && film.getGenres().size() > 0) {
Я вынес код, в отдельный метод, точнее два метода (т.к. логика в них похожа, но все же достаточно разная), потом откатил назад. Т.к.  по тестам мы не обновляем/создаем (mpa и/или genre) отдельно, то разбивать в данный момент, в этом не вижу смысла. 
PS:  Относится и к замечанию ниже.

2023-03-27 18:04 UTC, zg-devj commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            if (film.getGenres() != null && film.getGenres().size() >= 0) {
Выше описал ситуацию.

2023-03-27 18:07 UTC, zg-devj commented
Спасибо за ваши комментарии.

2023-03-28 13:39 UTC, TomattmanYandex requested changes
Привет, изначальная схема базы была лучше, в нынешней есть дупликация данных, это противоречит третьей нормальной форме,
Необходимо удалить поле rate, а сам рейтинг высчитывать по количеству лайков

2023-03-28 18:52 UTC, zg-devj commented
Спасибо. Исправил.

2023-03-29 16:31 UTC, TomattmanYandex approved these changes
Аргументы аргументны, принято

2023-03-29 16:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dto/FilmRateDto.java
> +public class FilmRateDto extends Film {
хороший вариант, разве что так как у нас нету прямой связи между объектом и таблицей, можно было поле  оставить у обьекта фильма

2023-03-29 17:14 UTC, merged